### ISSUE TITLE
Windows Defender identifies mtk_uartboot as malware and moves it to quarantine.

### ISSUE THREAD

**Issue by jmwoods301** [981213/mtk_uartboot#1]
Just an FYI...

As the title states, Defender doesn't like mtk_uartboot, and quarantines it.

Users will need to go into Virus & Threat Protection > Protection History and restore it.

**Comment by 981213** [comment]
Huh. That's strange. The binaries are built and uploaded with GitHub Action.

I've submitted it to https://www.microsoft.com/en-us/wdsi/filesubmission/

Let's see if anything comes out of that.

**Comment by 981213** [comment]
Microsoft fixed that. :D
