### ISSUE TITLE
Doesn't work on ARM (Not a bug, just wanting to leave a comment)

### ISSUE THREAD

**Issue by LitCastVlog** [981213/mtk_uartboot#3]
not an issue with the program itself, just wanted to comment if you could possibly release an ARM version (if it's even possible) to be used with a Raspberry Pi 4 (I use one as my serial adapter, router is connected to UART4 on the RPI since i don't have a usb uart adapter)

**Comment by 981213** [comment]
I suppose you could [install a rust toolchain](https://www.rust-lang.org/tools/install), clone the source code and build it yourself?
