### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dangowrt** [981213/mtk_uartboot#5]
I don't find any information about code license in this repository.
If you haven't decided yet, imho AGPL would be a good choice :)
Given, of course, that mtk_uartboot is not a derivative work of [bypass_util](https://github.com/MTK-bypass/bypass_utility) which would make it GPL-3.0 (or later?). I'm not a lawyer, but I wouldn't consider it derivative work in the sense of the GPL.

**Comment by 981213** [comment]
> imho AGPL would be a good choice :)

Agree. I've put AGPLv3 as the license of this repo.
